<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="studentdata.aspx.cs" Inherits="gridviewpagewebform.studentdata" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            margin-left: 25px;
        }
        .auto-style2 {
            margin-left: 125px;
            margin-top: 12px;
        }
        .auto-style3 {
            margin-left: 25px;
            margin-top: 36px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
        <asp:FileUpload ID="FileUpload1" runat="server" />
        <asp:Button ID="Button1" runat="server" CssClass="auto-style1" OnClick="Button1_Click" Text="submit" Width="86px" />
        <asp:Button ID="AddNewRecord" runat="server" CssClass="auto-style3" Height="35px" OnClick="Button2_Click1" Text="AddNewRecord" Width="108px" />
        
        <asp:Button ID="btnDownloadPDF" runat="server" Text="Download PDF" OnClick="btnDownloadPDF_Click" />

        <asp:Button ID="btnDownloadExcel" runat="server" Text="Download Excel" OnClick="btnDownloadExcel_Click" />

        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" CssClass="auto-style2" DataKeyNames="id" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="422px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="rollnumber" HeaderText="rollnumber" SortExpression="rollnumber" />
                <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                <asp:BoundField DataField="phoenumber" HeaderText="phoenumber" SortExpression="phoenumber" />
            </Columns>
            <EditRowStyle BackColor="#7C6F57" />
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#E3EAEB" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F8FAFA" />
            <SortedAscendingHeaderStyle BackColor="#246B61" />
            <SortedDescendingCellStyle BackColor="#D4DFE1" />
            <SortedDescendingHeaderStyle BackColor="#15524A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:gridviewwebformConnectionString3 %>" DeleteCommand="DELETE FROM [studenttbl] WHERE [id] = @id" InsertCommand="INSERT INTO [studenttbl] ([name], [rollnumber], [phoenumber], [address]) VALUES (@name, @rollnumber, @phoenumber, @address)" ProviderName="<%$ ConnectionStrings:gridviewwebformConnectionString3.ProviderName %>" SelectCommand="SELECT * FROM [studenttbl]" UpdateCommand="UPDATE [studenttbl] SET [name] = @name, [rollnumber] = @rollnumber, [phoenumber] = @phoenumber, [address] = @address WHERE [id] = @id">
            <DeleteParameters>
                <asp:Parameter Name="id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="rollnumber" Type="String" />
                <asp:Parameter Name="phoenumber" Type="Int32" />
                <asp:Parameter Name="address" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="rollnumber" Type="String" />
                <asp:Parameter Name="phoenumber" Type="Int32" />
                <asp:Parameter Name="address" Type="String" />
                <asp:Parameter Name="id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
